apiVersion: v1
kind: Template
metadata:
  annotations:
    description: 'ELIMINA: BuildConfig, Image Stream, Deployment Config,  Replication
      Controller,  Route, Servicio y  ConfigMap'
    iconClass: fa fa-trash
    openshift.io/display-name: (>) Eliminar Aplicación
  creationTimestamp: null
  name: delete.yaml
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: delete-app-pipeline
    name: delete-app-pipeline
  spec:
    source:
      contextDir: null
      git:
        ref: master
        uri: http://git.bancogalicia.com.ar/SacaTuTurno/DevOps.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_PROYECTO
          value: ${PARAM_PROJ_NAME}
        jenkinsfilePath: pipelines/delete.js
      type: JenkinsPipeline
parameters:
- description: Nombre del Proyecto (Ej. sacatuturno-dev)
  displayName: Nombre del Proyecto
  name: PARAM_PROJ_NAME
  required: true
  value: sacatuturno-dev
